name: On PR
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: fregante/setup-git-user@v2
      - run: git commit -m "PR open" --no-edit --allow-empty
      - run: git push
